name = "cellflow-backend"
main = "src/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cellflow"
database_id = "9cf58daf-93aa-4fb6-829e-9fc5c9d40e80"
migrations_dir = "migrations"

[vars]
AUTH_URL = "http://localhost:8787/api/auth"
